package com.marz.soporte.controller;
import com.marz.soporte.dto.*;import com.marz.soporte.entity.*;import com.marz.soporte.exception.GlobalExceptionHandler;import com.marz.soporte.security.*;import com.marz.soporte.service.*;import org.junit.jupiter.api.Test;import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;import org.springframework.context.annotation.Import;import org.springframework.http.MediaType;import org.springframework.security.core.userdetails.UserDetailsService;import org.springframework.security.test.context.support.WithMockUser;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;import org.springframework.beans.factory.annotation.Autowired;import java.time.Instant;import java.util.List;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.when;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest({SolicitudController.class,ComentarioController.class,UsuarioController.class})
@Import({SecurityConfig.class,JwtAuthenticationFilter.class,JwtAuthenticationEntryPoint.class,JwtAccessDeniedHandler.class,GlobalExceptionHandler.class})
class Sprint2SecurityControllerTest{
 @Autowired MockMvc mvc;@MockitoBean SolicitudService solicitudes;@MockitoBean ComentarioService comentarios;@MockitoBean UsuarioService usuarios;@MockitoBean JwtService jwt;@MockitoBean UserDetailsService details;
 @Test @WithMockUser(username="coord@x",roles="COORDINADOR") void coordinadorAsignaAgente()throws Exception{when(solicitudes.asignar(1L,2L,"coord@x")).thenReturn(respuesta());mvc.perform(patch("/api/solicitudes/1/asignacion").contentType(MediaType.APPLICATION_JSON).content("{\"agenteId\":2}")).andExpect(status().isOk());}
 @Test @WithMockUser(roles="SOLICITANTE") void solicitanteNoAsigna()throws Exception{mvc.perform(patch("/api/solicitudes/1/asignacion").contentType(MediaType.APPLICATION_JSON).content("{\"agenteId\":2}")).andExpect(status().isForbidden());}
 @Test @WithMockUser(username="agente@x",roles="AGENTE") void agenteAgregaComentario()throws Exception{when(comentarios.crear(1L,"Trabajo","agente@x")).thenReturn(new ComentarioResponse(1L,"Trabajo",Instant.now(),new AutorComentarioResponse(2L,"Agente",Rol.AGENTE)));mvc.perform(post("/api/solicitudes/1/comentarios").contentType(MediaType.APPLICATION_JSON).content("{\"contenido\":\"Trabajo\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.autor.rol").value("AGENTE"));}
 @Test @WithMockUser(roles="AGENTE") void comentarioVacioDevuelve400()throws Exception{mvc.perform(post("/api/solicitudes/1/comentarios").contentType(MediaType.APPLICATION_JSON).content("{\"contenido\":\" \"}")).andExpect(status().isBadRequest());}
 @Test @WithMockUser(username="agente@x",roles="AGENTE") void agenteCambiaEstado()throws Exception{when(solicitudes.cambiarEstado(1L,EstadoSolicitud.EN_PROCESO,"agente@x")).thenReturn(respuesta());mvc.perform(patch("/api/solicitudes/1/estado").contentType(MediaType.APPLICATION_JSON).content("{\"estado\":\"EN_PROCESO\"}")).andExpect(status().isOk());}
 @Test @WithMockUser(username="sol@x",roles="SOLICITANTE") void propietarioConfirmaCierre()throws Exception{when(solicitudes.confirmarCierre(1L,"sol@x")).thenReturn(respuesta());mvc.perform(patch("/api/solicitudes/1/confirmar-cierre")).andExpect(status().isOk());}
 @Test @WithMockUser(username="sol@x",roles="SOLICITANTE") void reaperturaSinMotivoDevuelve400()throws Exception{mvc.perform(patch("/api/solicitudes/1/reabrir").contentType(MediaType.APPLICATION_JSON).content("{\"motivo\":\"\"}")).andExpect(status().isBadRequest());}
 @Test @WithMockUser(roles="AGENTE") void agenteNoConfirmaCierre()throws Exception{mvc.perform(patch("/api/solicitudes/1/confirmar-cierre")).andExpect(status().isForbidden());}
 @Test @WithMockUser(roles="COORDINADOR") void listaSoloAgentesActivos()throws Exception{when(usuarios.agentesActivos()).thenReturn(List.of(new UsuarioResumenResponse(2L,"Agente","a@x",Rol.AGENTE)));mvc.perform(get("/api/usuarios/agentes")).andExpect(status().isOk()).andExpect(jsonPath("$[0].correo").value("a@x")).andExpect(jsonPath("$[0].password").doesNotExist());}
 @Test @WithMockUser(username="auditor@x",roles="AUDITOR") void auditorAccedeADetalleSoloLectura()throws Exception{when(solicitudes.detalle(1L,"auditor@x")).thenReturn(respuesta());mvc.perform(get("/api/solicitudes/1")).andExpect(status().isOk());}
 private SolicitudResponse respuesta(){return new SolicitudResponse(1L,"T","D",CategoriaSolicitud.SOFTWARE,Instant.now(),EstadoSolicitud.NUEVO,Prioridad.MEDIA);}
}
