import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { finalize, forkJoin } from 'rxjs';
import { CambioPrioridad, Categoria, Estado, FiltroSolicitud, Prioridad, Solicitud, UsuarioResumen } from '../../core/models/solicitud.model';
import { SolicitudesService } from '../../core/services/solicitudes.service';
import { StatusBadgeComponent } from '../../shared/status-badge.component';
import { FeedbackComponent } from '../../shared/feedback.component';

@Component({selector:'app-solicitudes-coordinador',imports:[DatePipe,FormsModule,RouterLink,StatusBadgeComponent,FeedbackComponent],template:`
 <div class="page-head"><div><p class="eyebrow">COORDINACIÓN</p><h1>Gestión de solicitudes</h1><p>Prioriza y asigna las solicitudes recibidas.</p></div></div>
 @if(message()){<app-feedback [type]="messageType()" [message]="message()"/>}
 <section class="card filters-card"><div class="filters-head"><div><strong>Filtros de gestión</strong><span>Combina criterios para localizar solicitudes</span></div><button class="button secondary compact" type="button" [disabled]="exporting()" (click)="exportCsv()">{{exporting()?'Exportando…':'Exportar CSV'}}</button></div>
 <form class="filters-grid" (ngSubmit)="applyFilters()">
  <label>Estado<select name="estado" [(ngModel)]="filters.estado"><option value="">Todos</option>@for(v of states;track v){<option [value]="v">{{v}}</option>}</select></label>
  <label>Prioridad<select name="prioridad" [(ngModel)]="filters.prioridad"><option value="">Todas</option>@for(v of priorities;track v){<option [value]="v">{{v}}</option>}</select></label>
  <label>Categoría<select name="categoria" [(ngModel)]="filters.categoria"><option value="">Todas</option>@for(v of categories;track v){<option [value]="v">{{v}}</option>}</select></label>
  <label>Agente<select name="agenteId" [(ngModel)]="filters.agenteId"><option value="">Todos</option>@for(a of agents();track a.id){<option [ngValue]="a.id">{{a.nombre}}</option>}</select></label>
  <label>Fecha desde<input name="fechaDesde" type="date" [(ngModel)]="filters.fechaDesde"></label>
  <label>Fecha hasta<input name="fechaHasta" type="date" [(ngModel)]="filters.fechaHasta"></label>
  <div class="filter-actions"><button class="button primary" type="submit" [disabled]="loading()">Aplicar filtros</button><button class="button secondary" type="button" [disabled]="loading()" (click)="clearFilters()">Limpiar filtros</button></div>
 </form></section>
 @if(loading()){<div class="state-card"><span class="spinner"></span><h2>Cargando solicitudes</h2></div>}
 @else if(error()){<div class="state-card"><span class="state-icon">!</span><h2>No pudimos cargar la gestión</h2><button class="button secondary" (click)="load()">Reintentar</button></div>}
 @else if(!items().length){<div class="state-card"><span class="state-icon">✓</span><h2>No hay solicitudes registradas</h2></div>}
 @else{<section class="card table-card"><div class="table-summary"><strong>{{items().length}} solicitudes</strong><span>Prioridad, agente y acciones</span></div><div class="table-wrap"><table><thead><tr><th>ID / solicitud</th><th>Estado</th><th>Prioridad</th><th>Agente asignado</th><th>Acciones</th></tr></thead><tbody>
 @for(s of items();track s.id){<tr><td><span class="id">#{{s.id}}</span><br><strong>{{s.titulo}}</strong><br><small>{{s.fechaCreacion|date:'dd MMM yyyy'}}</small></td><td><app-status-badge [value]="s.estado"/></td><td><app-status-badge [value]="s.prioridad"/>@if(s.justificacionPrioridadAlta){<div class="history-note"><strong>Justificación:</strong> {{s.justificacionPrioridadAlta}}<br><strong>Fecha objetivo:</strong> {{s.fechaObjetivo|date:'dd MMM yyyy'}}</div>}</td><td><strong>{{s.agenteAsignado?.nombre || 'Sin asignar'}}</strong>@if(s.agenteAsignado?.correo){<br><small>{{s.agenteAsignado?.correo}}</small>}</td><td><div class="management-actions"><label>Prioridad<select class="priority-select" [value]="s.prioridad" [disabled]="busy().has(s.id)" (change)="selectPriority(s,$event)">@for(p of priorities;track p){<option [value]="p">{{p}}</option>}</select></label><label>Agente<select [ngModel]="s.agenteAsignado?.id ?? null" [disabled]="busy().has(s.id)" (ngModelChange)="assign(s,$event)"><option [ngValue]="null" disabled>Seleccionar</option>@for(a of agents();track a.id){<option [ngValue]="a.id">{{a.nombre}}</option>}</select></label><a class="text-link" [routerLink]="['/solicitudes',s.id]">Ver detalle →</a>@if(busy().has(s.id)){<span class="mini-spinner"></span>}</div></td></tr>}
 </tbody></table></div></section>}
 @if(highTarget();as s){<div class="modal-backdrop"><section class="card modal" role="dialog" aria-modal="true" aria-labelledby="alta-title"><h2 id="alta-title">Prioridad ALTA · #{{s.id}}</h2><p>Indica por qué requiere atención prioritaria y su fecha objetivo.</p><form (ngSubmit)="saveHigh()"><div class="field"><label for="justificacion">Justificación</label><textarea id="justificacion" name="justificacion" rows="4" maxlength="500" required [(ngModel)]="highJustification"></textarea><span class="field-hint">{{highJustification.length}} / 500</span>@if(highSubmitted()&&!highJustification.trim()){<span class="field-error">La justificación es obligatoria.</span>}</div><div class="field"><label for="fechaObjetivo">Fecha objetivo</label><input id="fechaObjetivo" name="fechaObjetivo" type="date" required [min]="today" [(ngModel)]="highDate">@if(highSubmitted()&&(!highDate||highDate<today)){<span class="field-error">Selecciona hoy o una fecha posterior.</span>}</div><div class="form-actions"><button type="button" class="button secondary" [disabled]="busy().has(s.id)" (click)="cancelHigh()">Cancelar</button><button class="button primary" [disabled]="busy().has(s.id)">Guardar prioridad</button></div></form></section></div>}
 `})
export class SolicitudesCoordinadorComponent implements OnInit{
 readonly items=signal<Solicitud[]>([]);readonly agents=signal<UsuarioResumen[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly exporting=signal(false);readonly busy=signal(new Set<number>());readonly message=signal('');readonly messageType=signal<'success'|'error'>('success');readonly highTarget=signal<Solicitud|null>(null);readonly highSubmitted=signal(false);readonly priorities:Prioridad[]=['BAJA','MEDIA','ALTA'];readonly states:Estado[]=['NUEVO','EN_PROCESO','RESUELTO','CERRADO','REABIERTO'];readonly categories:Categoria[]=['HARDWARE','SOFTWARE','ACCESO','RED','OTRO'];filters:{estado:Estado|'';prioridad:Prioridad|'';categoria:Categoria|'';agenteId:number|'';fechaDesde:string;fechaHasta:string}=this.emptyFilters();highJustification='';highDate='';readonly today=new Date().toISOString().slice(0,10);
 constructor(private api:SolicitudesService){}ngOnInit(){this.load();}
 load(){this.loading.set(true);this.error.set(false);forkJoin({items:this.api.todas(),agents:this.api.agentes()}).subscribe({next:r=>{this.items.set(r.items);this.agents.set(r.agents);this.loading.set(false);},error:()=>{this.error.set(true);this.loading.set(false);}});}
 applyFilters(){if(!this.validDates())return;this.loading.set(true);this.error.set(false);this.message.set('');this.api.todas(this.normalizedFilters()).pipe(finalize(()=>this.loading.set(false))).subscribe({next:x=>this.items.set(x),error:e=>{this.error.set(true);this.showError(e,'No se pudieron aplicar los filtros.');}});}
 clearFilters(){this.filters=this.emptyFilters();this.applyFilters();}
 exportCsv(){if(this.exporting()||!this.validDates())return;this.exporting.set(true);this.message.set('');this.api.exportar(this.normalizedFilters()).pipe(finalize(()=>this.exporting.set(false))).subscribe({next:r=>{const blob=r.body;if(!blob){this.messageType.set('error');this.message.set('El archivo exportado llegó vacío.');return;}const match=/filename="?([^";]+)"?/i.exec(r.headers.get('Content-Disposition')??'');const name=match?.[1]??'solicitudes.csv';const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);},error:e=>this.showError(e,'No se pudo exportar el archivo CSV.')});}
 selectPriority(s:Solicitud,event:Event){const select=event.target as HTMLSelectElement;const next=select.value as Prioridad;if(next===s.prioridad)return;if(next==='ALTA'){select.value=s.prioridad;this.highTarget.set(s);this.highJustification='';this.highDate='';this.highSubmitted.set(false);return;}this.updatePriority(s,{prioridad:next},select);}
 saveHigh(){this.highSubmitted.set(true);const s=this.highTarget();if(!s||!this.highJustification.trim()||this.highJustification.length>500||!this.highDate||this.highDate<this.today)return;this.updatePriority(s,{prioridad:'ALTA',justificacion:this.highJustification.trim(),fechaObjetivo:this.highDate});}
 cancelHigh(){this.highTarget.set(null);this.highSubmitted.set(false);}
 private updatePriority(s:Solicitud,data:CambioPrioridad,select?:HTMLSelectElement){this.setBusy(s.id,true);this.message.set('');this.api.cambiarPrioridad(s.id,data).pipe(finalize(()=>this.setBusy(s.id,false))).subscribe({next:x=>{this.replace(x);this.highTarget.set(null);this.messageType.set('success');this.message.set(`La prioridad de la solicitud #${s.id} se actualizó a ${x.prioridad}.`);},error:e=>{if(select)select.value=s.prioridad;this.showError(e,'No se pudo actualizar la prioridad. Se conservó el valor anterior.');}});}
 assign(s:Solicitud,agenteId:number|null){if(!agenteId||agenteId===s.agenteAsignado?.id)return;this.setBusy(s.id,true);this.message.set('');this.api.asignar(s.id,{agenteId}).pipe(finalize(()=>this.setBusy(s.id,false))).subscribe({next:x=>{this.replace(x);this.messageType.set('success');this.message.set(`La solicitud #${s.id} quedó asignada a ${x.agenteAsignado?.nombre}.`);},error:e=>this.showError(e,'No se pudo cambiar el agente. Se conservó la asignación anterior.')});}
 private replace(s:Solicitud){this.items.update(xs=>xs.map(x=>x.id===s.id?s:x));}private setBusy(id:number,on:boolean){this.busy.update(x=>{const n=new Set(x);on?n.add(id):n.delete(id);return n;});}private showError(e:HttpErrorResponse,fallback:string){this.messageType.set('error');this.message.set(e.error?.message||e.error?.mensaje||fallback);}
 private validDates(){if(this.filters.fechaDesde&&this.filters.fechaHasta&&this.filters.fechaDesde>this.filters.fechaHasta){this.messageType.set('error');this.message.set('La fecha desde no puede ser posterior a la fecha hasta.');return false;}return true;}
 private normalizedFilters():FiltroSolicitud{return Object.fromEntries(Object.entries(this.filters).filter(([,v])=>v!=='')) as FiltroSolicitud;}
 private emptyFilters(){return{estado:'' as Estado|'',prioridad:'' as Prioridad|'',categoria:'' as Categoria|'',agenteId:'' as number|'',fechaDesde:'',fechaHasta:''};}
}
