import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { finalize } from 'rxjs';
import { Prioridad, Solicitud } from '../../core/models/solicitud.model';
import { SolicitudesService } from '../../core/services/solicitudes.service';
import { StatusBadgeComponent } from '../../shared/status-badge.component';
import { FeedbackComponent } from '../../shared/feedback.component';

@Component({selector:'app-solicitudes-coordinador',imports:[DatePipe,StatusBadgeComponent,FeedbackComponent],template:`
 <div class="page-head"><div><p class="eyebrow">COORDINACIÓN</p><h1>Gestión de solicitudes</h1><p>Revisa y prioriza las solicitudes recibidas.</p></div></div>
 @if(message()){<app-feedback [type]="messageType()" [message]="message()"/>}
 @if(loading()){<div class="state-card"><span class="spinner"></span><h2>Cargando solicitudes</h2></div>}
 @else if(error()){<div class="state-card"><span class="state-icon">!</span><h2>No pudimos cargar las solicitudes</h2><button class="button secondary" (click)="load()">Reintentar</button></div>}
 @else if(!items().length){<div class="state-card"><span class="state-icon">✓</span><h2>No hay solicitudes registradas</h2><p>Las nuevas solicitudes aparecerán aquí.</p></div>}
 @else{<section class="card table-card"><div class="table-summary"><strong>{{items().length}} solicitudes</strong><span>Actualiza únicamente la prioridad</span></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Título</th><th>Categoría</th><th>Fecha</th><th>Estado</th><th>Prioridad actual</th><th>Cambiar prioridad</th></tr></thead><tbody>@for(s of items();track s.id){<tr><td class="id">#{{s.id}}</td><td><strong>{{s.titulo}}</strong></td><td>{{label(s.categoria)}}</td><td>{{s.fechaCreacion|date:'dd MMM yyyy'}}</td><td><app-status-badge [value]="s.estado"/></td><td><app-status-badge [value]="s.prioridad"/></td><td><select class="priority-select" [value]="s.prioridad" [disabled]="updating().has(s.id)" (change)="changePriority(s,$event)">@for(p of priorities;track p){<option [value]="p">{{p}}</option>}</select>@if(updating().has(s.id)){<span class="mini-spinner" aria-label="Actualizando"></span>}</td></tr>}</tbody></table></div></section>}`})
export class SolicitudesCoordinadorComponent implements OnInit{readonly items=signal<Solicitud[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly updating=signal(new Set<number>());readonly message=signal('');readonly messageType=signal<'success'|'error'>('success');readonly priorities:Prioridad[]=['BAJA','MEDIA','ALTA'];constructor(private api:SolicitudesService){}ngOnInit(){this.load();}load(){this.loading.set(true);this.error.set(false);this.api.todas().subscribe({next:x=>{this.items.set(x);this.loading.set(false);},error:()=>{this.error.set(true);this.loading.set(false);}});}changePriority(s:Solicitud,event:Event){const select=event.target as HTMLSelectElement;const next=select.value as Prioridad;if(next===s.prioridad)return;this.updating.update(set=>new Set(set).add(s.id));this.message.set('');this.api.cambiarPrioridad(s.id,next).pipe(finalize(()=>this.updating.update(set=>{const n=new Set(set);n.delete(s.id);return n;}))).subscribe({next:confirmed=>{this.items.update(xs=>xs.map(x=>x.id===s.id?confirmed:x));this.messageType.set('success');this.message.set(`La prioridad de la solicitud #${s.id} se actualizó a ${confirmed.prioridad}.`);},error:()=>{select.value=s.prioridad;this.messageType.set('error');this.message.set(`No se pudo actualizar la solicitud #${s.id}. Se conservó la prioridad anterior.`);}});}label(v:string){return v.charAt(0)+v.slice(1).toLowerCase();}}
