import { NEVER, of } from 'rxjs';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { Solicitud } from '../../core/models/solicitud.model';
import { SolicitudesService } from '../../core/services/solicitudes.service';
import { SolicitudesCoordinadorComponent } from './solicitudes-coordinador.component';
import { vi } from 'vitest';

describe('SolicitudesCoordinadorComponent',()=>{
 const solicitud:Solicitud={id:1,titulo:'Caso',descripcion:'Detalle',categoria:'RED',fechaCreacion:'2026-10-06',estado:'NUEVO',prioridad:'MEDIA'};
 it('exige justificación y fecha antes de enviar prioridad ALTA',()=>{const api={cambiarPrioridad:vi.fn()} as unknown as SolicitudesService;const component=new SolicitudesCoordinadorComponent(api);component.highTarget.set(solicitud);component.saveHigh();expect(component.highSubmitted()).toBe(true);expect(api.cambiarPrioridad).not.toHaveBeenCalled();});
 it('asigna un agente y actualiza la fila confirmada',()=>{const confirmada={...solicitud,agenteAsignado:{id:2,nombre:'Ana'}};const assign=vi.fn().mockReturnValue(of(confirmada));const api={asignar:assign} as unknown as SolicitudesService;const component=new SolicitudesCoordinadorComponent(api);component.items.set([solicitud]);component.assign(solicitud,2);expect(assign).toHaveBeenCalledWith(1,{agenteId:2});expect(component.items()[0].agenteAsignado?.nombre).toBe('Ana');});
 it('no consulta cuando el rango de fechas es inválido',()=>{const todas=vi.fn();const component=new SolicitudesCoordinadorComponent({todas} as unknown as SolicitudesService);component.filters.fechaDesde='2026-10-10';component.filters.fechaHasta='2026-10-01';component.applyFilters();expect(todas).not.toHaveBeenCalled();expect(component.message()).toContain('fecha desde');});
 it('limpia filtros y recupera el listado general',()=>{const todas=vi.fn().mockReturnValue(of([]));const component=new SolicitudesCoordinadorComponent({todas} as unknown as SolicitudesService);component.filters.estado='NUEVO';component.clearFilters();expect(todas).toHaveBeenCalledWith({});expect(component.filters.estado).toBe('');});
 it('evita una segunda exportación mientras descarga',()=>{const exportar=vi.fn().mockReturnValue(NEVER);const component=new SolicitudesCoordinadorComponent({exportar} as unknown as SolicitudesService);component.exportCsv();component.exportCsv();expect(exportar).toHaveBeenCalledTimes(1);expect(component.exporting()).toBe(true);});
 it('descarga el blob con el nombre del servidor y libera la URL',()=>{const response=new HttpResponse({body:new Blob(['csv']),headers:new HttpHeaders({'Content-Disposition':'attachment; filename="reporte.csv"'})});const exportar=vi.fn().mockReturnValue(of(response));const create=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:test');const revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const component=new SolicitudesCoordinadorComponent({exportar} as unknown as SolicitudesService);component.filters.prioridad='ALTA';component.exportCsv();expect(exportar).toHaveBeenCalledWith({prioridad:'ALTA'});expect(click).toHaveBeenCalled();expect(revoke).toHaveBeenCalledWith('blob:test');create.mockRestore();revoke.mockRestore();click.mockRestore();});
});
