import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { finalize, forkJoin } from 'rxjs';
import { CambioPrioridad, Prioridad, Solicitud, UsuarioResumen } from '../../core/models/solicitud.model';
import { SolicitudesService } from '../../core/services/solicitudes.service';
import { StatusBadgeComponent } from '../../shared/status-badge.component';
import { FeedbackComponent } from '../../shared/feedback.component';

@Component({selector:'app-solicitudes-coordinador',imports:[DatePipe,FormsModule,RouterLink,StatusBadgeComponent,FeedbackComponent],template:`
 <div class="page-head"><div><p class="eyebrow">COORDINACIÓN</p><h1>Gestión de solicitudes</h1><p>Prioriza y asigna las solicitudes recibidas.</p></div></div>
 @if(message()){<app-feedback [type]="messageType()" [message]="message()"/>}
 @if(loading()){<div class="state-card"><span class="spinner"></span><h2>Cargando solicitudes</h2></div>}
 @else if(error()){<div class="state-card"><span class="state-icon">!</span><h2>No pudimos cargar la gestión</h2><button class="button secondary" (click)="load()">Reintentar</button></div>}
 @else if(!items().length){<div class="state-card"><span class="state-icon">✓</span><h2>No hay solicitudes registradas</h2></div>}
 @else{<section class="card table-card"><div class="table-summary"><strong>{{items().length}} solicitudes</strong><span>Prioridad, agente y acciones</span></div><div class="table-wrap"><table><thead><tr><th>ID / solicitud</th><th>Estado</th><th>Prioridad</th><th>Agente asignado</th><th>Acciones</th></tr></thead><tbody>
 @for(s of items();track s.id){<tr><td><span class="id">#{{s.id}}</span><br><strong>{{s.titulo}}</strong><br><small>{{s.fechaCreacion|date:'dd MMM yyyy'}}</small></td><td><app-status-badge [value]="s.estado"/></td><td><app-status-badge [value]="s.prioridad"/>@if(s.justificacionPrioridadAlta){<div class="history-note"><strong>Justificación:</strong> {{s.justificacionPrioridadAlta}}<br><strong>Fecha objetivo:</strong> {{s.fechaObjetivo|date:'dd MMM yyyy'}}</div>}</td><td><strong>{{s.agenteAsignado?.nombre || 'Sin asignar'}}</strong>@if(s.agenteAsignado?.correo){<br><small>{{s.agenteAsignado?.correo}}</small>}</td><td><div class="management-actions"><label>Prioridad<select class="priority-select" [value]="s.prioridad" [disabled]="busy().has(s.id)" (change)="selectPriority(s,$event)">@for(p of priorities;track p){<option [value]="p">{{p}}</option>}</select></label><label>Agente<select [ngModel]="s.agenteAsignado?.id ?? null" [disabled]="busy().has(s.id)" (ngModelChange)="assign(s,$event)"><option [ngValue]="null" disabled>Seleccionar</option>@for(a of agents();track a.id){<option [ngValue]="a.id">{{a.nombre}}</option>}</select></label><a class="text-link" [routerLink]="['/solicitudes',s.id]">Ver detalle →</a>@if(busy().has(s.id)){<span class="mini-spinner"></span>}</div></td></tr>}
 </tbody></table></div></section>}
 @if(highTarget();as s){<div class="modal-backdrop"><section class="card modal" role="dialog" aria-modal="true" aria-labelledby="alta-title"><h2 id="alta-title">Prioridad ALTA · #{{s.id}}</h2><p>Indica por qué requiere atención prioritaria y su fecha objetivo.</p><form (ngSubmit)="saveHigh()"><div class="field"><label for="justificacion">Justificación</label><textarea id="justificacion" name="justificacion" rows="4" maxlength="500" required [(ngModel)]="highJustification"></textarea><span class="field-hint">{{highJustification.length}} / 500</span>@if(highSubmitted()&&!highJustification.trim()){<span class="field-error">La justificación es obligatoria.</span>}</div><div class="field"><label for="fechaObjetivo">Fecha objetivo</label><input id="fechaObjetivo" name="fechaObjetivo" type="date" required [min]="today" [(ngModel)]="highDate">@if(highSubmitted()&&(!highDate||highDate<today)){<span class="field-error">Selecciona hoy o una fecha posterior.</span>}</div><div class="form-actions"><button type="button" class="button secondary" [disabled]="busy().has(s.id)" (click)="cancelHigh()">Cancelar</button><button class="button primary" [disabled]="busy().has(s.id)">Guardar prioridad</button></div></form></section></div>}
 `})
export class SolicitudesCoordinadorComponent implements OnInit{
 readonly items=signal<Solicitud[]>([]);readonly agents=signal<UsuarioResumen[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly busy=signal(new Set<number>());readonly message=signal('');readonly messageType=signal<'success'|'error'>('success');readonly highTarget=signal<Solicitud|null>(null);readonly highSubmitted=signal(false);readonly priorities:Prioridad[]=['BAJA','MEDIA','ALTA'];highJustification='';highDate='';readonly today=new Date().toISOString().slice(0,10);
 constructor(private api:SolicitudesService){}ngOnInit(){this.load();}
 load(){this.loading.set(true);this.error.set(false);forkJoin({items:this.api.todas(),agents:this.api.agentes()}).subscribe({next:r=>{this.items.set(r.items);this.agents.set(r.agents);this.loading.set(false);},error:()=>{this.error.set(true);this.loading.set(false);}});}
 selectPriority(s:Solicitud,event:Event){const select=event.target as HTMLSelectElement;const next=select.value as Prioridad;if(next===s.prioridad)return;if(next==='ALTA'){select.value=s.prioridad;this.highTarget.set(s);this.highJustification='';this.highDate='';this.highSubmitted.set(false);return;}this.updatePriority(s,{prioridad:next},select);}
 saveHigh(){this.highSubmitted.set(true);const s=this.highTarget();if(!s||!this.highJustification.trim()||this.highJustification.length>500||!this.highDate||this.highDate<this.today)return;this.updatePriority(s,{prioridad:'ALTA',justificacion:this.highJustification.trim(),fechaObjetivo:this.highDate});}
 cancelHigh(){this.highTarget.set(null);this.highSubmitted.set(false);}
 private updatePriority(s:Solicitud,data:CambioPrioridad,select?:HTMLSelectElement){this.setBusy(s.id,true);this.message.set('');this.api.cambiarPrioridad(s.id,data).pipe(finalize(()=>this.setBusy(s.id,false))).subscribe({next:x=>{this.replace(x);this.highTarget.set(null);this.messageType.set('success');this.message.set(`La prioridad de la solicitud #${s.id} se actualizó a ${x.prioridad}.`);},error:e=>{if(select)select.value=s.prioridad;this.showError(e,'No se pudo actualizar la prioridad. Se conservó el valor anterior.');}});}
 assign(s:Solicitud,agenteId:number|null){if(!agenteId||agenteId===s.agenteAsignado?.id)return;this.setBusy(s.id,true);this.message.set('');this.api.asignar(s.id,{agenteId}).pipe(finalize(()=>this.setBusy(s.id,false))).subscribe({next:x=>{this.replace(x);this.messageType.set('success');this.message.set(`La solicitud #${s.id} quedó asignada a ${x.agenteAsignado?.nombre}.`);},error:e=>this.showError(e,'No se pudo cambiar el agente. Se conservó la asignación anterior.')});}
 private replace(s:Solicitud){this.items.update(xs=>xs.map(x=>x.id===s.id?s:x));}private setBusy(id:number,on:boolean){this.busy.update(x=>{const n=new Set(x);on?n.add(id):n.delete(id);return n;});}private showError(e:HttpErrorResponse,fallback:string){this.messageType.set('error');this.message.set(e.error?.message||e.error?.mensaje||fallback);}
}
