package com.marz.soporte.service;
import com.marz.soporte.entity.*;import com.marz.soporte.repository.*;import org.junit.jupiter.api.*;import org.springframework.security.access.AccessDeniedException;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;
class ComentarioServiceTest{
 private ComentarioRepository comentarios;private SolicitudRepository solicitudes;private UsuarioRepository usuarios;private ComentarioService service;private Usuario propietario,agente,coord;private Solicitud solicitud;
 @BeforeEach void init(){comentarios=mock(ComentarioRepository.class);solicitudes=mock(SolicitudRepository.class);usuarios=mock(UsuarioRepository.class);service=new ComentarioService(comentarios,solicitudes,usuarios);propietario=u(1,"p@x",Rol.SOLICITANTE);agente=u(2,"a@x",Rol.AGENTE);coord=u(3,"c@x",Rol.COORDINADOR);solicitud=new Solicitud();solicitud.setId(8L);solicitud.setSolicitante(propietario);solicitud.setAgenteAsignado(agente);when(solicitudes.findById(8L)).thenReturn(Optional.of(solicitud));for(Usuario u:List.of(propietario,agente,coord))when(usuarios.findByCorreoIgnoreCase(u.getCorreo())).thenReturn(Optional.of(u));}
 @Test void asignadoCreaComentarioConAutorYFecha(){when(comentarios.save(any())).thenAnswer(i->{Comentario c=i.getArgument(0);c.setId(1L);return c;});var r=service.crear(8L," Trabajo realizado ",agente.getCorreo());assertThat(r.contenido()).isEqualTo("Trabajo realizado");assertThat(r.autor().id()).isEqualTo(2);assertThat(r.fechaCreacion()).isNotNull();verify(comentarios).save(any());}
 @Test void noAsignadoNoComenta(){Usuario otro=u(4,"o@x",Rol.AGENTE);when(usuarios.findByCorreoIgnoreCase(otro.getCorreo())).thenReturn(Optional.of(otro));assertThatThrownBy(()->service.crear(8L,"x",otro.getCorreo())).isInstanceOf(AccessDeniedException.class);}
 @Test void devuelveComentariosEnOrdenDelRepositorio(){Comentario a=c(1,Instant.parse("2026-01-01T00:00:00Z"));Comentario b=c(2,Instant.parse("2026-01-02T00:00:00Z"));when(comentarios.findBySolicitudIdOrderByFechaCreacionAsc(8L)).thenReturn(List.of(a,b));assertThat(service.listar(8L,propietario.getCorreo())).extracting("id").containsExactly(1L,2L);}
 @Test void coordinadorConsultaComentarios(){when(comentarios.findBySolicitudIdOrderByFechaCreacionAsc(8L)).thenReturn(List.of());assertThat(service.listar(8L,coord.getCorreo())).isEmpty();}
 private Usuario u(long id,String correo,Rol rol){Usuario u=new Usuario();u.setId(id);u.setCorreo(correo);u.setNombre("U");u.setRol(rol);u.setActivo(true);return u;}private Comentario c(long id,Instant fecha){Comentario c=new Comentario();c.setId(id);c.setSolicitud(solicitud);c.setAutor(agente);c.setContenido("x");c.setFechaCreacion(fecha);return c;}
}
