import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { SolicitudesService } from './solicitudes.service';
import { API_URL } from '../config/api.config';
import { Solicitud } from '../models/solicitud.model';

describe('SolicitudesService', () => {
 let service:SolicitudesService;let http:HttpTestingController;
 const solicitud:Solicitud={id:7,titulo:'Error de acceso',descripcion:'No puedo ingresar',categoria:'ACCESO',fechaCreacion:'2026-10-06T10:00:00Z',estado:'NUEVO',prioridad:'MEDIA'};
 beforeEach(()=>{TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting()]});service=TestBed.inject(SolicitudesService);http=TestBed.inject(HttpTestingController);});afterEach(()=>http.verify());
 it('crea una solicitud enviando solo los campos permitidos',()=>{const body={titulo:'Error de acceso',descripcion:'No puedo ingresar',categoria:'ACCESO' as const};let result:Solicitud|undefined;service.crear(body).subscribe(x=>result=x);const req=http.expectOne(`${API_URL}/api/solicitudes`);expect(req.request.method).toBe('POST');expect(req.request.body).toEqual(body);req.flush(solicitud);expect(result).toEqual(solicitud);});
 it('carga Mis solicitudes',()=>{let result:Solicitud[]=[];service.mias().subscribe(x=>result=x);const req=http.expectOne(`${API_URL}/api/solicitudes/mias`);expect(req.request.method).toBe('GET');req.flush([solicitud]);expect(result).toEqual([solicitud]);});
 it('genera filtros combinados sin parámetros vacíos',()=>{service.todas({estado:'EN_PROCESO',prioridad:'ALTA',categoria:undefined,agenteId:2,fechaDesde:'',fechaHasta:'2026-12-31'}).subscribe();const req=http.expectOne(r=>r.url===`${API_URL}/api/solicitudes`);expect(req.request.params.get('estado')).toBe('EN_PROCESO');expect(req.request.params.get('prioridad')).toBe('ALTA');expect(req.request.params.get('agenteId')).toBe('2');expect(req.request.params.get('fechaHasta')).toBe('2026-12-31');expect(req.request.params.has('categoria')).toBe(false);expect(req.request.params.has('fechaDesde')).toBe(false);req.flush([]);});
 it('exporta como blob reutilizando filtros',()=>{service.exportar({estado:'CERRADO',prioridad:'ALTA'}).subscribe();const req=http.expectOne(r=>r.url===`${API_URL}/api/solicitudes/exportar`);expect(req.request.responseType).toBe('blob');expect(req.request.params.get('estado')).toBe('CERRADO');expect(req.request.params.get('prioridad')).toBe('ALTA');req.flush(new Blob(['ID,Titulo']));});
 it('envía justificación y fecha para prioridad ALTA',()=>{const body={prioridad:'ALTA' as const,justificacion:'Impacto crítico',fechaObjetivo:'2026-10-10'};service.cambiarPrioridad(7,body).subscribe();const req=http.expectOne(`${API_URL}/api/solicitudes/7/prioridad`);expect(req.request.method).toBe('PATCH');expect(req.request.body).toEqual(body);req.flush({...solicitud,prioridad:'ALTA'});});
 it('lista agentes activos y asigna uno',()=>{service.agentes().subscribe();http.expectOne(`${API_URL}/api/usuarios/agentes`).flush([]);service.asignar(7,{agenteId:2}).subscribe();const req=http.expectOne(`${API_URL}/api/solicitudes/7/asignacion`);expect(req.request.method).toBe('PATCH');expect(req.request.body).toEqual({agenteId:2});req.flush(solicitud);});
 it('lista las solicitudes asignadas al agente',()=>{service.asignadas().subscribe();const req=http.expectOne(`${API_URL}/api/solicitudes/asignadas`);expect(req.request.method).toBe('GET');req.flush([solicitud]);});
 it('envía el estado exacto en una transición',()=>{service.cambiarEstado(7,{estado:'EN_PROCESO'}).subscribe();const req=http.expectOne(`${API_URL}/api/solicitudes/7/estado`);expect(req.request.body).toEqual({estado:'EN_PROCESO'});req.flush({...solicitud,estado:'EN_PROCESO'});});
 it('confirma cierre y reabre con motivo',()=>{service.confirmarCierre(7).subscribe();const close=http.expectOne(`${API_URL}/api/solicitudes/7/confirmar-cierre`);expect(close.request.method).toBe('PATCH');close.flush({...solicitud,estado:'CERRADO'});service.reabrir(7,{motivo:'Sigue fallando'}).subscribe();const reopen=http.expectOne(`${API_URL}/api/solicitudes/7/reabrir`);expect(reopen.request.body).toEqual({motivo:'Sigue fallando'});reopen.flush({...solicitud,estado:'REABIERTO'});});
});
